services:
  - type: web
    name: campos-cadilhe
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    autoDeploy: true
    healthCheckPath: /search
    envVars:
      - key: NODE_ENV
        value: production
